# Generated by Django 5.2.1 on 2025-05-11 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='num_ratings',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
