# Generated by Django 5.2.1 on 2025-05-11 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_product_product_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='search_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
