# Generated by Django 5.2.1 on 2025-05-11 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0004_product_search_count'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='product',
            unique_together={('title', 'product_link')},
        ),
    ]
