# Generated by Django 5.2.1 on 2025-05-11 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0005_alter_product_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricehistory',
            name='price',
            field=models.DecimalField(decimal_places=2, default=-1, max_digits=10),
        ),
    ]
